spring:
# 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.17.14:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ifonly


# mybatis配置
mybatis:
  type-aliases-package: com.zl.pojo

# 日志配置
logging:
  level:
    root: warn
    com.zl: info
  file: log/blog-pro.log

server:
  port: 80

